"""
    AI USAGE: The _get helper function was developed by Claude. I used claude as a way to teach me
    and demonstrate how to make this effective requests helper function of which I could use.This
    helped make my learning process more enjoyable and showed me how to write good code for reaching
    external API's. Claude also suggested the get_fixture and get_head_to_head functions and the
    choice of API-Football endpoints, which I typed in, debugged and documented myself. Code for the 
    get_review function was generated by claude. 
"""

import os
import requests
from dotenv import load_dotenv
from flask_restful import reqparse, abort
import sqlite3

load_dotenv() # Load in Environment Variable

# API Configuration from API-Football API
BASE_URL = "https://v3.football.api-sports.io"
API_KEY = os.environ.get("API_KEY")

class FixtureNotFound(Exception):
    """
    The API answered to fixtures but the match was not found.
    """

class ExternalAPIError(Exception):
    """
    The API did not answer or other errors occured.
    """

class DuplicateReview(Exception):
    "Found a duplicate review in the database."
class ReviewNotFound(Exception):
    "The review was not found in the database."
class Forbidden(Exception):
    "User is forbidden to modify this review."

# PARSER HELPER FUNCTIONS
def parse_review() -> dict:
    "Read and Validate the body of POST /reviews"
    parser = reqparse.RequestParser()
    parser.add_argument("fixture_id", type=int, required=True, location='json',
                        help="fixture_id is required and must be an integer.")
    parser.add_argument("rating", type=int, required=True, location='json',
                        help="rating is required and must be an integer.")
    parser.add_argument("review", type=str, required=False, location='json')
    return parser.parse_args()

def parse_review_changes() -> dict:
    "Read and validate the body of PATCH /reviews/<id>. Both fields are optional."
    parser = reqparse.RequestParser()
    parser.add_argument("rating", type=int, required=False, location='json',
                        help="rating must be an integer.")
    parser.add_argument("review", type=str, required=False, location='json')
    changes = parser.parse_args()

    if changes["rating"] is None and changes["review"] is None:
        abort(400, message="Provide a rating and/or review to update.")
    if changes["rating"] is not None and not 1 <= changes["rating"] <= 10:
        abort(400, message="rating must be between 1 and 10.")
    if changes["review"] is not None and not changes["review"].strip():
        abort(400, message="review cannot be blank.")
    return changes

# CLAUDE
def parse_filters() -> dict:
    "Read the optional query parameters of GET /reviews."
    parser = reqparse.RequestParser()
    parser.add_argument("league", type=str, required=False, location='args')
    return parser.parse_args()

def create_review(db, user_id: int, fixture_id: int, rating: int, review: str):
    fixture = get_fixture(fixture_id)

    try:
        review_id = db.insert_review(user_id, fixture_id, fixture, rating, review)
    except sqlite3.IntegrityError:
        raise DuplicateReview(fixture_id)

    return db.get_review(review_id)

def get_review(db, review_id: int) -> dict:
    "Return one review by id. Raises ReviewNotFound if it does not exist."
    review = db.get_review(review_id)
    if review is None:
        raise ReviewNotFound(review_id)
    return review

def list_reviews(db, league: str | None) -> list[dict]:
    return db.list_reviews(league)

def patch_review(db, review_id: int, rating: int | None, review: str | None) -> dict:
    db.update_review(review_id, rating, review)
    return db.get_review(review_id)

def delete_review(db, review_id: int) -> None:
    db.delete_review(review_id)

# CLAUDE CREATED THIS FUNCTION
def _get(path, params):
    """
    This helper function will send a get request to the football-api with the pre-loaded key
    in the header. This will take in a path to the specific endpoint it wants and the
    parameters needed for the query. It will return the JSON the the response.
    """
    try:
        resp = requests.get(
            f"{BASE_URL}{path}",
            headers={"x-apisports-key": API_KEY},
            params=params,
            timeout=10,
        )
        resp.raise_for_status()
    except requests.RequestException as e:
        raise ExternalAPIError(str(e))

    data = resp.json()
    if data.get("errors"):
        raise ExternalAPIError(str(data["errors"]))
    return data.get("response", [])

def get_fixture(fixture_id):
    """
    This function will look up matches by ID.
    It recieves the fixture ID and will return Python dict of the details of the match.
    """
    results = _get("/fixtures", {"id": fixture_id})
    if not results:
        raise FixtureNotFound(fixture_id)

    match = results[0]
    return {
        "home_id": match["teams"]["home"]["id"],
        "away_id": match["teams"]["away"]["id"],
        "home_team": match["teams"]["home"]["name"],
        "away_team": match["teams"]["away"]["name"],
        "home_goals": match["goals"]["home"],
        "away_goals": match["goals"]["away"],
        "league": match["league"]["name"],
        "match_date": match["fixture"]["date"],
    }

def get_head_to_head(home_id, away_id, last=5):
    """
    This function will look up head-to-head matches of teams.
    It will take in a home and an away id for teams as well as the specified number of games wanted.
    It will return details about those specific fixtures in python dictionary.
    """
    response = _get("/fixtures/headtohead", {"h2h": f"{home_id}-{away_id}", "last": last})
    return [
        {
            "date": m["fixture"]["date"],
            "home_team": m["teams"]["home"]["name"],
            "away_team": m["teams"]["away"]["name"],
            "score": f'{m["goals"]["home"]}-{m["goals"]["away"]}',
        }
        for m in response
    ]